### ISSUE TITLE
When no wheel available, all output of build  process is swallowed, making it appear as if pip froze

### ISSUE THREAD

**Issue by untitaker** [getsentry/milksnake#1]
This has also been an issue with snaek. When you install a package without wheels, installation might take a very long time (particularly when `rustc` is involved). The user isn't notified about that and might get the impression that the installation froze.

I attempted a patch to forward all output from the build functions (i.e. cargo's output), but it seems like this requires a lot of workarounds.

**Comment by mitsuhiko** [comment]
You can show the build output by enabling verbose mode in pip:

```
pip install -v --editable .
```

This might make sense for filing against pip (eg: maybe show a yarn style one liner progress bar with stdout?)

Like this:

<img src="https://github.com/mitsuhiko/indicatif/raw/master/screenshots/yarn.gif?raw=true">

**Comment by untitaker** [comment]
I think `-v` is fine for my usecase, thanks.
