### ISSUE TITLE
Clarify what's wrong with cffi's setuptools support

### ISSUE THREAD

**Issue by ionelmc** [getsentry/milksnake#3]
In the readme it say "CFFI's setuptools support alone does not properly work with wheels" - but what does that exactly mean? Some examples and clarifications would help a lot.

**Comment by mitsuhiko** [comment]
I think this is left as an exercise for the reader :)

**Comment by ionelmc** [comment]
Come on @mitsuhiko this is really low effort response :) Surely you can string a sentence about what problems you had building wheels.

**Comment by mitsuhiko** [comment]
f22df90f4fea59c9de1848a6d30454f6e2ba670d

**Comment by ionelmc** [comment]
@mitsuhiko Well, better but still not 100% clear. But now looking over the code it looks like milkshake only adds the possibility of forcing universal wheels - so that's the problem with tags right?

Also, worth mentioning that milkshake is designed to use cffi in ABI out-of-line mode (and generates the cffi boilerplate for you)?

**Comment by mitsuhiko** [comment]
Milksnake does a bunch of things, mostly related to invoking build tools and bundling resources.

**Comment by ionelmc** [comment]
Ah yes, not the best wording, I meant „regarding the cffi setuptools support, only adds ...”.
