### ISSUE TITLE
Global inline flags bug since Python 3.11

### ISSUE THREAD

**Issue by NieWil** [getsentry/milksnake#31]
Hello,
The regular expression [here ](https://github.com/getsentry/milksnake/blob/ef0723e41df23d8f6357570c69c1e69cb31f9e9e/milksnake/ffi.py#L8)is no longer tolerated by the version of [Python 3.11](https://docs.python.org/uk/3.12/whatsnew/3.11.html#changes-in-the-python-api)
"Global inline flags (e.g. (?i)) can now only be used at the start of the regular expressions"

Small suggested fix:  `_directive_re = re.compile(r'(?m)^\s*#.*?$')`

**Comment by alexbrasetvik** [comment]
Fixed by #32.

**Comment by NieWil** [comment]
Thanks  

> Fixed by #32.
