### ISSUE TITLE
Cargo build target is not matched to Python platform

### ISSUE THREAD

**Issue by filmor** [getsentry/milksnake#8]
Currently, it's quite easy to erronously compile the Rust library against an incompatible toolchain (in my case: i686-... vs x86_64-...). This is caught by running `python setup.py test`, but it would be nice if the build already fails in this case.

**Comment by mitsuhiko** [comment]
I wonder if it makes sense to land helpers for rust compilation in some sort of milksnake contrib that fixes this. This currently is definitely out of scope for milksnake in its current form.
